In [1]:
import numpy as np

In [13]:
a = np.array([1,3,4,5,2,234])  #onr dimension array
print(a)
b = np.array([[1,2,3,4,9],
              [5,6,7,8,10]])
print(b)

[  1   3   4   5   2 234]
[[ 1  2  3  4  9]
 [ 5  6  7  8 10]]


In [14]:
#Shape , size , dimension
print(b.ndim) #dimension
print(b.shape) #shape == rows , coloums
print(b.size) #size ===> no of elements
print(b.itemsize) #itemsize shows the memory allocated or used by the element in array



2
(2, 5)
10
8


In [20]:
print(b[1,:]) # full row
print(b[:,3]) #full coloumn
print(b[1, 1:-1:2]) # [rowidx , startidx:endidx:stepcount]

[ 5  6  7  8 10]
[4 8]
[6 8]


3D - array


In [ ]:
c = np.array([ [[1,2],[3,4]] ,[[5,6],[7,8]]])

print(c[0,1,1]) # idx , idx , idx

4


Initialzing of all Different kind of array


In [29]:
Zeros_matrix = np.zeros((2,3),dtype = 'int8')
print(Zeros_matrix)
print(Zeros_matrix.dtype)
print(Zeros_matrix.size)

[[0 0 0]
 [0 0 0]]
int8
6


In [ ]:
ones_matrix = np.ones((3,3) , dtype='int16') # np.ones((shape),dtype)
print(ones_matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
any_matrix = np.full(c.shape,99,dtype='int32')# np.full((shape),value,dtype) , for shape we can provide number or by refering shape of other arrray
print(any_matrix)

[[[99 99]
  [99 99]]

 [[99 99]
  [99 99]]]
